logging:
  level:
    org.springframework.core.env: warn
    org.springframework.jndi: warn

server:  port: 9003
  compression:
    enabled: true
    mime-types: application/json,text/css,text/html
    min-response-size: 2048
  error:
    include-message: always
    whitelabel:
      enabled: false
  forward-headers-strategy: native

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  task:
    execution:
      thread-name-prefix: initializr-

initializr:
  env:
    repositories:
      sonatype-snapshots:
        name: Sonatype Snapshots
        url: https://oss.sonatype.org/content/repositories/snapshots/
        snapshotsEnabled: true
  dependencies:
    - name: Developer Tools
      content:
        - name: Spring Boot DevTools
          id: devtools
          groupId: org.springframework.boot
          artifactId: spring-boot-devtools
          scope: runtime
          description: Provides fast application restarts, LiveReload, and configurations for enhanced development experience.
          starter: false
          links:
            - rel: reference
              href: https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#using-boot-devtools
        - name: Lombok
          id: lombok
          groupId: org.projectlombok
          artifactId: lombok
          scope: annotationProcessor
          description: Java annotation library which helps to reduce boilerplate code.
          starter: false
        - name: Spring Configuration Processor
          id: configuration-processor
          groupId: org.springframework.boot
          artifactId: spring-boot-configuration-processor
          scope: annotationProcessor
          description: Generate metadata for developers to offer contextual help and "code completion" when working with custom configuration keys (ex.application.properties/.yml files).
          starter: false
          links:
            - rel: reference
              href: https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#configuration-metadata-annotation-processor
    - name: 基础技术组件
      content:
        - name: Framework
          id: Framework
          groupId: com.croot
          artifactId: croot_framework_starter
          description: 脚手架基础框架，集成了日志，关系型多数据源，缓存，线程池，swagger等组件功能.
          

          
    - name: 扩展技术组件
      content:
        - name: Security
          id: Security
          groupId: com.croot
          artifactId: croot_security_starter
          description: 此组件用于集成spring Security的配置使用.
       
        - name: Batch
          id: Batch
          groupId: com.croot
          artifactId: croot_batch_starter
          description: 此组件用于集成spring batch的配置使用.

        - name: Statemachine
          id: Statemachine
          groupId: com.croot
          artifactId: croot_statemachine_starter
          description: 此组件用于集成spring statemachine的配置使用.          

        - name: Websocket
          id: Websocket
          groupId: com.croot
          artifactId: croot_websocket_starter
          description: 此组件用于定义websocket的配置使用.

        - name: Monitor
          id: Monitor
          groupId: com.croot
          artifactId: croot_monitor_starter
          description: 此组件用于监控后台日志及服务情况.
          
        - name: Preview
          id: Preview
          groupId: com.croot
          artifactId: croot_preview_starter
          description: 此组件用于在线文档（暂支持markdown）的配置使用.          
          
        - name: Redis
          id: Redis
          groupId: com.croot
          artifactId: croot_redis_starter
          description: 此组件用于多Redis配置使用.
          
        - name: Storage
          id: Storage
          groupId: com.croot
          artifactId: croot_storage_starter
          description: 此组件用于定义文件上传下载的配置使用.
          
        - name: MongoDB
          id: MongoDB
          groupId: com.croot
          artifactId: croot_multimongo_starter
          description: 多mongoDB支持 .
       
        - name: POI
          id: POI
          groupId: com.croot
          artifactId: croot_poi_starter
          description: 此组件基于Apache POI统一定义读写Excel通用方法.      
          
        - name: Ldap
          id: Ldap
          groupId: com.croot
          artifactId: croot_ldap_starter
          description: 此组件用于远程ldap server认证的配置.   
          
        - name: OAuth2 Server
          id: OAuth2 Server
          groupId: com.croot
          artifactId: croot_oauth2_server_starter
          description: 此组件用于集成OAuth2 Server的配置.   
          
        - name: OAuth2 Resource
          id: OAuth2 Resource
          groupId: com.croot
          artifactId: croot_oauth2_resource_starter
          description: 此组件用于集成OAuth2 Resource的配置. 
          
        - name: OAuth2 Client
          id: OAuth2 Client
          groupId: com.croot
          artifactId: croot_oauth2_client_starter
          description: 此组件用于集成OAuth2 Client的配置.                                            

    - name: Cloud技术组件
      content:
        - name: Eureka
          id: Eureka
          groupId: com.croot
          artifactId: croot_cloud_eureka_client_starter
          description: 此组件用于集成Eureka服务.
          
        - name: Consul
          id: Consul
          groupId: com.croot
          artifactId: croot_cloud_consul_starter
          description: 此组件用于集成Consul服务.
          
        - name: Zookeeper
          id: Zookeeper
          groupId: com.croot
          artifactId: croot_cloud_zookeeper_starter
          description: 此组件用于集成Zookeeper服务.          
   
        - name: Nacos
          id: Nacos
          groupId: com.croot
          artifactId: croot_cloud_nacos_starter
          description: 此组件用于集成Nacos服务.                    

    - name: 公共业务组件
      content:
        - name: Access
          id: Access
          groupId: com.croot
          artifactId: croot_access_starter
          description: 此组件用于调用MDS/FAS 业务接口.
          
          
   
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive.
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Maven POM
      id: maven-build
      description: Generate a Maven pom.xml.
      tags:
        build: maven
        format: build
      default: false
      action: /pom.xml
    
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  javaVersions:
    - id: 14
      default: false
    - id: 11
      default: false
    - id: 1.8
      name: 8
      default: true
  languages:
    - name: Java
      id: java
      default: true
  bootVersions:
    - name : 2.3.0(SNAPSHOT)
      id: 2.3.0-SNAPSHOT
      default: true
#    - name : 2.2.5.RELEASE
#      id: 2.2.5.RELEASE
#      default: true
#    - name : 2.2.4.RELEASE
#      id: 2.2.4.RELEASE
#      default: false

---

spring:
  profiles: dev
  resources:
    static_locations:
      - file:start-client/public/
  devtools:
    restart:
      additional_paths:
        - start-client/public/
      additional_exclude: "**/*.js,**/*.css,**/*.html"
